REFERENCE_GENOME_NAME: "hg38"
ALIGN_THREADS: 8


## Container paths & versions
MUTECT_VERSION: "4.4.0.0"
BWAMEM2_VERSION: "2.2.1"
SRATOOLS_VERSION: "3.0.1"

## Analysis paths
TEMP_DIR: "/tmp/"
#SCRATCH_DIR: "/gpfs/scratch/culibl01/"
PROD_DIR: "/gpfs/data/petljaklab/data/"
SCRATCH_DIR: "/gpfs/data/petljaklab/data/"
## Resource paths
# Probably add these as a module sometime?
ALN_REFERENCES:
  hg19: "/gpfs/data/petljaklab/resources/hg19/pipeline_resources/genome/bwa/hg19.fa"
  hg38: "/gpfs/data/petljaklab/resources/hg38/pipeline_resources/genome/bwa/hg38.fa"
  mm10: "/gpfs/data/petljaklab/resources/mm10/pipeline_resources/genome/bwa/mm10.fa"

FA_PATHS:
  hg19: "/gpfs/data/petljaklab/resources/hg19/pipeline_resources/genome/fasta/hg19.fa"
  hg38: "/gpfs/data/petljaklab/resources/hg38/pipeline_resources/genome/fasta/hg38.fa"
  mm10: "/gpfs/data/petljaklab/resources/mm10/pipeline_resources/genome/fasta/mm10.fa"
db: "petljakdb"

bench: False

chromosomes:
  hg19: 
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
    - "13"
    - "14"
    - "15"
    - "16"
    - "17"
    - "18"
    - "19"
    - "20"
    - "21"
    - "22"
    - "X"
  hg38:
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr9"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chr20"
    - "chr21"
    - "chr22"
    - "chrX"
  mm10:
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr9"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chrX"


clusters:
  default:
    med:
      "petljaklab,cpu_medium"
    fat:
      "petljaklab,fn_medium,cpu_medium"
    short:
      "petljaklab,cpu_short"
    dev:
      "petljaklab,cpu_dev"
  cpu:
    med:
      "cpu_medium"
    fat:
      "fn_medium"
    short:
      "cpu_short"
    dev:
      "cpu_dev"
  petljak:
    med:
      "petljaklab"
    short:
      "petljaklab"
    fat:
      "petljaklab"
    dev:
      "petljaklab"

parts: "default"